services:
  postgres:
    image: postgres:latest
    container_name: postgres_disponibilidade_SSL
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_disponibilidade_SSL:/var/lib/postgresql/postgres_data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_disponibilidade_SSL
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - grafana_disponibilidade_SSL:/var/lib/grafana

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: ["python3", "/app/executar_testes.py"]

volumes:
  postgres_disponibilidade_SSL:
  grafana_disponibilidade_SSL: