{
 "title": "Validação_SSL",
 "description": "Testes de validação de certificados",
 "time": { "from": "2025-02-25T14:18:55.000Z", "to": "2025-02-25T14:22:31.000Z" },
 "templating": {
  "list": [
   {
    "name": "Sistemas_SSL",
    "query": "SELECT DISTINCT sistema FROM ssl_test_results;"
   }
  ]
 },
 "panels": [
  {
   "title": "Certificados Testados",
   "type": "stat",
   "description": "Aqui temos o número total de certificados Testados",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT (DISTINCT sistema) AS Cert_Vulneráveis FROM ssl_test_results;"
    }
   ]
  },
  {
   "title": "Certificados sem Vulnerabilidade",
   "type": "stat",
   "description": "Aqui temos o número total de certificados Sem Vulnerabilidade",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT (DISTINCT sistema) AS Cert_Sem_Vulneráveis FROM ssl_test_results WHERE vulneravel = False"
    }
   ]
  },
  {
   "title": "Certificados perto de vencer, 15 a 4 dias",
   "type": "stat",
   "description": "Certificados prox de vencer, com 15 dias de validade",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT (DISTINCT sistema) AS PROX_VENCER\r\nFROM ssl_test_results\r\nWHERE dias_restantes BETWEEN 4 AND 15;  -- Aqui você pode definir um dia viavel para a corporação, nesse exemplo considerei 15 a 4 dias\r\n"
    }
   ]
  },
  {
   "title": "Certificados Vulneraveis",
   "type": "stat",
   "description": "Aqui temos o número total de certificados Vulneráveis",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT (DISTINCT sistema) AS Cert_Vulneráveis FROM ssl_test_results WHERE vulneravel = True"
    }
   ]
  },
  {
   "title": "Certificados Validade Ok, 30 ou mais dias:",
   "type": "stat",
   "description": "Certificados prox de vencer, com 15 dias de validade",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT (DISTINCT sistema) AS PROX_VENCER\r\nFROM ssl_test_results\r\nWHERE dias_restantes >= 30;  -- Aqui você pode definir um dia viavel para a corporação\r\n"
    }
   ]
  },
  {
   "title": "Certificados perto de vencer, 1 a 3 dias",
   "type": "stat",
   "description": "Certificados prox de vencer, com 15 dias de validade",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT (DISTINCT sistema) AS PROX_VENCER\r\nFROM ssl_test_results\r\nWHERE dias_restantes BETWEEN 1 AND 3;  -- se seja certificdos com 1 a 3 dias para vencer"
    }
   ]
  },
  {
   "title": "Certificados Vencidos!!!",
   "type": "stat",
   "description": "Certificados prox de vencer, com 15 dias de validade",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  COUNT (DISTINCT sistema) AS Cert_Vencidos\r\nFROM ssl_test_results\r\nWHERE dias_restantes <= 0;  -- se seja certificdos com 1 a 3 dias para vencer"
    }
   ]
  },
  {
   "title": "Lista de todos os certificados ",
   "type": "table",
   "description": "Lista de todos os certificados com dias restantes e criteriedade",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (sistema) \r\n    sistema AS dominio,\r\n    dias_restantes,\r\n    CASE \r\n        WHEN dias_restantes >= 31 THEN '🟢 Seguro'\r\n        WHEN dias_restantes BETWEEN 15 AND 30 THEN '🟡 Atenção'\r\n        WHEN dias_restantes BETWEEN 1 AND 14 THEN '🔴 Crítico'\r\n        ELSE '⚠️ Expirado'\r\n    END AS status\r\nFROM ssl_test_results\r\nORDER BY sistema, dias_restantes ASC;\r\n"
    }
   ]
  },
  {
   "title": "Certificadoscom vulnerabilidades",
   "type": "table",
   "description": "Lista de todos os Certificados com vulnerabilidades",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sistema AS dominio,\r\n    STRING_AGG(vulnerabilidade, ', ') AS vulnerabilidades -- Une todas as vulnerabilidades em uma única linha\r\nFROM ssl_test_results\r\nWHERE vulneravel = TRUE  -- Filtra apenas os que possuem vulnerabilidades\r\nGROUP BY sistema, dias_restantes\r\nORDER BY dias_restantes ASC;\r\n"
    }
   ]
  }
 ]
}