{
 "title": "Disponibilidade_Sites",
 "description": "Nesse Dashboard conseguimos acompanhar metricas de disponibilidade dos sites",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Variavel_sites",
    "query": "SELECT DISTINCT sistema FROM disponibilidade_sistemas;"
   }
  ]
 },
 "panels": [
  { "title": "Dash Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sistemas no ar",
   "type": "stat",
   "description": "Aqui apesentamos quantos sistemas estão disponiveis",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_sistemas\r\nFROM (\r\n    SELECT DISTINCT ON (sistema) sistema\r\n    FROM disponibilidade_sistemas\r\n    WHERE status = TRUE\r\n    AND data_hora_teste >= NOW() - INTERVAL '2.5 minutes'  -- FILTRA APENAS TESTES RECENTES\r\n    ORDER BY sistema, data_hora_teste DESC\r\n) subquery;\r\n"
    }
   ]
  },
  {
   "title": "Sistemas fora do ar",
   "type": "stat",
   "description": "Aqui apesentamos quantos sistemas estão indisponíveis",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_sistemas\r\nFROM (\r\n    SELECT DISTINCT ON (sistema) sistema\r\n    FROM disponibilidade_sistemas\r\n    WHERE status = FALSE\r\n    AND data_hora_teste >= NOW() - INTERVAL '2.5 minutes'  -- FILTRA APENAS TESTES RECENTES\r\n    ORDER BY sistema, data_hora_teste DESC\r\n) subquery;\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sistema, data_hora_teste,\r\n       CASE \r\n           -- TESTE DESATUALIZADO (NÃO HOUVE TESTE NOS ÚLTIMOS 2 MINUTOS)\r\n           WHEN data_hora_teste < NOW() - INTERVAL '2.5 minutes' THEN 3 \r\n           -- TESTE RECENTE ONLINE\r\n           WHEN status = TRUE THEN 1\r\n           -- TESTE RECENTE OFFLINE\r\n           ELSE 2\r\n       END AS status_code\r\nFROM (\r\n    -- Seleciona apenas o último teste de cada sistema\r\n    SELECT DISTINCT ON (sistema) sistema, data_hora_teste, status\r\n    FROM disponibilidade_sistemas\r\n    ORDER BY sistema, data_hora_teste DESC\r\n) subquery\r\nORDER BY sistema DESC;\r\n"
    }
   ]
  },
  {
   "title": "Feedbacck do dia",
   "type": "table",
   "description": "Aqui temos um resumo geral de eventuais problemas que ocorreram durante  o dia!",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sistema,\r\n    MIN(data_hora_teste) AS horario_primeira_falha, -- Mostra a primeira vez que o erro ocorreu\r\n    COUNT(*) AS qtd_falhas, -- Número total de vezes que esse erro ocorreu\r\n    LPAD(FLOOR((COUNT(*) * 2) / 60)::TEXT, 2, '0') || ':' || \r\n    LPAD(((COUNT(*) * 2) % 60)::TEXT, 2, '0') AS tempo_fora_formatado, -- Tempo total offline\r\n    erro -- Mostra apenas uma vez cada erro\r\nFROM disponibilidade_sistemas\r\nWHERE status = FALSE\r\nAND data_hora_teste >= DATE_TRUNC('day', NOW())  -- Filtra apenas o dia atual\r\nGROUP BY sistema, erro -- Agrupamos por sistema e pelo erro específico\r\nORDER BY qtd_falhas DESC;\r\n"
    }
   ]
  },
  { "title": "Relatório testes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Ultimo teste válido",
   "type": "stat",
   "description": "Aqui conseguimos verificar quando ocorreu o ultimo teste válido",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT data_hora_teste\r\nFROM disponibilidade_sistemas \r\nWHERE status = True \r\nAND sistema = '$Variavel_sites'\r\nORDER BY data_hora_teste DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Total Positivos",
   "type": "stat",
   "description": "Aqui conseguimos verificar total de testes válidos",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) AS TOTAL\r\nFROM disponibilidade_sistemas \r\nWHERE status = True \r\nAND sistema = '$Variavel_sites';"
    }
   ]
  },
  {
   "title": "Desempenho do sistema",
   "type": "timeseries",
   "description": "Aqui acompanhamos cada teste, sabendo quando estava no ar ou não.\nOs testes ocorrem a cada 2 min.\n\nRegras para gráfico cortado:\n2 min\t1 teste perdido (ainda normal)\n4 min\t2 testes perdidos (suspeito)\n6 min\t3 testes perdidos (provável falha no monitoramento)\n10+ min\tAlgo realmente errado (problema confirmado)",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sistema, \r\n    data_hora_teste,\r\n    CASE \r\n        WHEN status = TRUE THEN 1  -- ONLINE\r\n        ELSE 0  -- OFFLINE\r\n    END AS status_num\r\nFROM disponibilidade_sistemas\r\nWHERE sistema = '$Variavel_sites'\r\nORDER BY data_hora_teste DESC;\r\n"
    }
   ]
  },
  {
   "title": "Ultimo teste inválido",
   "type": "stat",
   "description": "Aqui conseguimos verificar quando ocorreu o ultimo teste inválido",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT data_hora_teste\r\nFROM disponibilidade_sistemas \r\nWHERE status = False \r\nAND sistema = '$Variavel_sites'\r\nORDER BY data_hora_teste DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Total Falhos",
   "type": "stat",
   "description": "Aqui conseguimos verificar total de testes falhos.",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT (*) AS TOTAL\r\nFROM disponibilidade_sistemas \r\nWHERE status = False \r\nAND sistema = '$Variavel_sites';"
    }
   ]
  },
  {
   "title": "Falhas hoje",
   "type": "stat",
   "description": "Aqui conseguimos verificar quantas falhas tivemos hoje",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) AS qtd_falhas -- Número total de vezes que esse erro ocorreu\r\nFROM disponibilidade_sistemas\r\nWHERE status = FALSE\r\nAND sistema = '$Variavel_sites'\r\nAND data_hora_teste >= DATE_TRUNC('day', NOW())  -- Filtra apenas o dia atual\r\nGROUP BY sistema;\r\n"
    }
   ]
  },
  {
   "title": "Tempo fora hoje",
   "type": "stat",
   "description": "Aqui conseguimos verificar quanto tempo o sistema ficou fora hoje.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sistema,\r\n    COUNT(*) AS qtd_falhas, -- Número total de vezes que esse erro ocorreu\r\n    LPAD(FLOOR((COUNT(*) * 2) / 60)::TEXT, 2, '0') || ':' || \r\n    LPAD(((COUNT(*) * 2) % 60)::TEXT, 2, '0') AS tempo_fora -- Tempo total offline\r\nFROM disponibilidade_sistemas\r\nWHERE status = FALSE\r\nAND sistema = '$Variavel_sites'\r\nAND data_hora_teste >= DATE_TRUNC('day', NOW())  -- Filtra apenas o dia atual\r\nGROUP BY sistema;\r\n"
    }
   ]
  },
  {
   "title": "Falhas hoje",
   "type": "stat",
   "description": "Aqui conseguimos verificar quantas falhas tivemos hoje",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) AS qtd_falhas  -- Número total de testes falhos\r\nFROM disponibilidade_sistemas\r\nWHERE status = FALSE\r\nAND sistema = '$Variavel_sites'\r\nAND data_hora_teste >= DATE_TRUNC('week', NOW());  -- Filtra apenas os registros da semana atual (segunda-feira 00:00)\r\n"
    }
   ]
  },
  {
   "title": "Tempo fora semana",
   "type": "stat",
   "description": "Aqui conseguimos verificar quanto tempo o sistema ficou fora na semana atual.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sistema,\r\n    COUNT(*) AS qtd_falhas, -- Número total de vezes que esse erro ocorreu\r\n    LPAD(FLOOR((COUNT(*) * 2) / 60)::TEXT, 2, '0') || ':' || \r\n    LPAD(((COUNT(*) * 2) % 60)::TEXT, 2, '0') AS tempo_fora -- Tempo total offline\r\nFROM disponibilidade_sistemas\r\nWHERE status = FALSE\r\nAND sistema = '$Variavel_sites'\r\nAND data_hora_teste >= DATE_TRUNC('week', NOW())  -- Filtra apenas os registros da semana atual (segunda-feira 00:00)\r\nGROUP BY sistema;\r\n"
    }
   ]
  },
  {
   "title": "Falhas hoje",
   "type": "stat",
   "description": "Aqui conseguimos verificar quantas falhas tivemos hoje",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) AS qtd_falhas  -- Número total de testes falhos\r\nFROM disponibilidade_sistemas\r\nWHERE status = FALSE\r\nAND sistema = '$Variavel_sites'\r\nAND data_hora_teste >= DATE_TRUNC('month', NOW());  -- Filtra apenas os registros do mês atual\r\n"
    }
   ]
  },
  {
   "title": "Tempo fora mês",
   "type": "stat",
   "description": "Aqui conseguimos verificar quanto tempo o sistema ficou fora na do mês.",
   "gridPos": { "h": 5, "w": 3, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    sistema,\r\n    COUNT(*) AS qtd_falhas, -- Número total de vezes que esse erro ocorreu\r\n    LPAD(FLOOR((COUNT(*) * 2) / 60)::TEXT, 2, '0') || ':' || \r\n    LPAD(((COUNT(*) * 2) % 60)::TEXT, 2, '0') AS tempo_fora -- Tempo total offline\r\nFROM disponibilidade_sistemas\r\nWHERE status = FALSE\r\nAND sistema = '$Variavel_sites'\r\nAND data_hora_teste >= DATE_TRUNC('month', NOW())  -- Filtra apenas os registros do mês atual (1º dia do mês 00:00)\r\nGROUP BY sistema;\r\n"
    }
   ]
  },
  {
   "title": "Logs de erro do sistema",
   "type": "table",
   "description": "Aqui conseguimos acompanhar todos os logs de erro do sistema elecionado.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT erro ,data_hora_teste FROM disponibilidade_sistemas WHERE sistema = '$Variavel_sites' AND status = False ORDER BY data_hora_teste DESC;"
    }
   ]
  },
  {
   "title": "Latência ",
   "type": "timeseries",
   "description": "Aqui podemos acompanhar como está a latência do tempo do teste.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 38 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    data_hora_teste AS time,  -- O Grafana exige uma coluna chamada \"time\"\r\n    AVG(tempo_resposta) AS media_tempo_resposta\r\nFROM disponibilidade_sistemas\r\nWHERE sistema = '$Variavel_sites'\r\nAND data_hora_teste >= NOW() - INTERVAL '1 day'  -- Últimos 24h\r\nGROUP BY data_hora_teste\r\nORDER BY data_hora_teste ASC;\r\n"
    }
   ]
  }
 ]
}